#server.port=8085
#spring.redis.host=localhost
#spring.redis.port=6379

spring:
  flyway:
    locations: classpath:db/migration
    schemas: postgres
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}?currentSchema=postgres
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379